module.exports=function(grunt){

	grunt.initConfig({
		//copy命令
		copy:{
			main:{
				files:[
					{expand:true,cwd:'src/',src:['**'],dest:'dest/'}
				]
			}
		},
		/*
		*文件合并命令
		*/
		concat:{
			js:{
				src:['src/**/*.js'],
				dest:'dist/main.js'
			},
			css:{
				src:['src/style/**/*.css'],
				dest:'dist/style/main.css'
			}
		},
		/**
		*js压缩合并命令
		*/
		uglify:{
			options: {
      			banner: '/*hello world\n haha*/\n'
    		},
			dist:{
				files:{'dest/main.min.js':['src/lib/underscore.js','src/lib/**/*.js','src/app.js','src/module/**/*.js']}
			}
		},
		/**
		*css合并压缩命令
		*/
		cssmin:{
			main:{
				files:{'dist/style/main.css':['src/style/**/*.css']}
			}
		},
		/**
		*观察任务
		*/
		watch:{
			files:['src/**/*.js'],
			tasks:['uglify']
		}
	});

	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-concat');
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.loadNpmTasks('grunt-contrib-copy');
	grunt.loadNpmTasks('grunt-contrib-cssmin');

	grunt.registerTask('default',['uglify']);
}
